import React, { useCallback, useEffect, useState } from "react";
import { FaBox, FaPlus, FaTrash } from "react-icons/fa";
import AdminNavbar from "../../../components/admin/Navbar";
import AdminPageHeader from "../../../components/admin/AdminPageHeader";
import AdminDialog from "../../../components/admin/AdminDialog";
import { createAdminProduct, deleteAdminProduct, getAdminOrders, getAdminProduct, getAdminProducts, updateAdminOrderStatus, updateAdminProduct } from "../../../lib/commerce";
import { imgUrl } from "../../../lib/api";
import styles from "./AdminProducts.module.css";
import { useAdminDialog } from "../../../hooks/useAdminDialog";

const empty = { name: "", sku: "", description: "", images: [], primary_index: 0 };
export default function AdminProducts() {
  const adminDialog = useAdminDialog();
  const [products, setProducts] = useState([]); const [orders, setOrders] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [existingImages, setExistingImages] = useState([]); const [removedImages, setRemovedImages] = useState([]); const [primaryImageId, setPrimaryImageId] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const [p, o] = await Promise.all([getAdminProducts(), getAdminOrders()]); setProducts(p.products || []); setOrders(o.orders || []); } catch (err) { setMessage(err?.response?.data?.message || "Unable to load Product Bank."); } }, []);
  useEffect(() => { load(); }, [load]);
  const resetForm = () => { setForm(empty); setEditing(null); setExistingImages([]); setRemovedImages([]); setPrimaryImageId(""); };
  const edit = async (id) => { const data = await getAdminProduct(id); const product = data.product; setEditing(product.id); setForm({ name: product.name, sku: product.sku || "", description: product.description || "", images: [], primary_index: 0 }); setExistingImages(product.images || []); setPrimaryImageId(String(product.images?.find((image) => Number(image.is_primary))?.id || "")); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { const body = new FormData(); body.append("name", form.name); body.append("sku", form.sku); body.append("description", form.description); body.append("primary_index", form.primary_index); body.append("remove_image_ids", removedImages.join(",")); if (primaryImageId) body.append("primary_image_id", primaryImageId); else if (editing && form.images.length) body.append("new_primary_index", form.primary_index); form.images.forEach((file) => body.append("images", file)); if (editing) await updateAdminProduct(editing, body); else await createAdminProduct(body); const wasEditing = Boolean(editing); resetForm(); setMessage(wasEditing ? "Product updated." : "Product saved."); await load(); } catch (err) { setMessage(err?.response?.data?.message || "Unable to save product."); } finally { setBusy(false); } };
  const remove = async (id) => { const confirmed = await adminDialog.confirm({ title: "Delete product?", message: "Products already used by a heist will be archived instead of permanently removed.", confirmLabel: "Delete product", tone: "danger" }); if (!confirmed) return; await deleteAdminProduct(id); await load(); };
  return <div className={styles.page}><AdminNavbar/><main className={styles.main}><AdminPageHeader eyebrow="Heists" title="Product Bank" description="Create reusable physical rewards and manage product fulfillment." />{message ? <div className={styles.message}>{message}</div> : null}
    <section className={styles.grid}><form className={styles.panel} onSubmit={submit}><h2><FaPlus/> {editing ? "Edit product" : "Add product"}</h2><label>Name<input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></label><label>SKU (optional)<input value={form.sku} onChange={(e) => setForm({...form,sku:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={(e) => setForm({...form,description:e.target.value})}/></label>{existingImages.length ? <div className={styles.existingImages}>{existingImages.map((image) => <label key={image.id} className={removedImages.includes(image.id) ? styles.removedImage : ""}><img src={imgUrl(image.image_path)} alt=""/><input type="radio" name="primary" checked={primaryImageId === String(image.id)} disabled={removedImages.includes(image.id)} onChange={() => setPrimaryImageId(String(image.id))}/><span>Primary</span><button type="button" onClick={() => setRemovedImages((ids) => ids.includes(image.id) ? ids.filter((id) => id !== image.id) : [...ids, image.id])}>{removedImages.includes(image.id) ? "Keep" : "Remove"}</button></label>)}</div> : null}<label>Product images<input required={!editing && !existingImages.length} type="file" accept="image/*" multiple onChange={(e) => setForm({...form,images:[...e.target.files],primary_index:0})}/></label>{form.images.length ? <label>Primary new image<select value={form.primary_index} onChange={(e) => { setPrimaryImageId(""); setForm({...form,primary_index:Number(e.target.value)}); }}>{form.images.map((file,index)=><option key={`${file.name}-${index}`} value={index}>{file.name}</option>)}</select></label>:null}<button disabled={busy}>{busy?"Saving...":editing?"Update product":"Save to Product Bank"}</button>{editing ? <button type="button" onClick={resetForm}>Cancel edit</button> : null}</form>
      <section className={styles.panel}><h2><FaBox/> Saved products</h2><div className={styles.list}>{products.map((product)=><article key={product.id}>{product.primary_image?<img src={imgUrl(product.primary_image)} alt={product.name}/>:<span className={styles.placeholder}/>}<div><strong>{product.name}</strong><small>{product.sku||"No SKU"} · {product.heist_count} Heist(s)</small></div><span className={styles.rowActions}><button onClick={()=>edit(product.id)}>Edit</button><button onClick={()=>remove(product.id)} aria-label={`Delete ${product.name}`}><FaTrash/></button></span></article>)}</div></section></section>
    <section className={styles.panel}><h2>Product orders</h2><div className={styles.orders}>{orders.length?orders.map((order)=><article key={order.id}><div><strong>{order.order_reference}</strong><span>{order.product_names || `${order.item_count} product(s)`} · Heist #{order.heist_ids}</span><span>{order.recipient_name} · {order.phone_number}</span><small>{order.detailed_address}, {order.state}</small><a href={`https://www.google.com/maps?q=${order.latitude},${order.longitude}`} target="_blank" rel="noreferrer">Open captured location</a></div><select value={order.status} onChange={async(e)=>{await updateAdminOrderStatus(order.id,e.target.value);await load();}}>{["pending","processing","shipped","delivered"].map(status=><option value={status} key={status} disabled={!({pending:["pending","processing"],processing:["processing","shipped"],shipped:["shipped","delivered"],delivered:["delivered"]}[order.status]||[]).includes(status)}>{status}</option>)}</select></article>):<p>No product orders yet.</p>}</div></section>
    <AdminDialog {...adminDialog.dialogProps}/>
  </main></div>;
}
